# Generated by Django 5.0.8 on 2024-08-24 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Library', '0011_rename_task_id_answer_task_and_more'),
        ('Singleplayer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='SPGame',
        ),
        migrations.RenameModel(
            old_name='Quiz_contains_Quiztask',
            new_name='SPGame_contains_Quiztask',
        ),
        migrations.RenameField(
            model_name='spgame',
            old_name='title',
            new_name='name',
        ),
    ]
