# Generated by Django 5.0.8 on 2024-08-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Singleplayer', '0002_rename_quiz_spgame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spgame',
            name='completed_at',
            field=models.DateTimeField(default=None),
        ),
    ]
