# Generated by Django 5.0.8 on 2024-08-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Singleplayer', '0004_alter_spgame_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spgame_contains_quiztask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spgame_contains_quiztask',
            name='correct_answered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
