# Generated by Django 5.0.8 on 2024-08-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Singleplayer', '0005_alter_spgame_contains_quiztask_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spgame_contains_quiztask',
            old_name='quiz_id',
            new_name='game_id',
        ),
    ]
