# Generated by Django 5.0.8 on 2024-08-25 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library', '0011_rename_task_id_answer_task_and_more'),
        ('Singleplayer', '0006_rename_quiz_id_spgame_contains_quiztask_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spgame_contains_quiztask',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='spgame_contains_quiztask',
            old_name='task_id',
            new_name='task',
        ),
        migrations.AddField(
            model_name='spgame',
            name='pool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Library.quizpool'),
            preserve_default=False,
        ),
    ]
