# Generated by Django 5.0.8 on 2024-08-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Singleplayer', '0008_spgame_contains_quiztask_selected_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spgame',
            name='correct_percent',
            field=models.FloatField(default=0),
        ),
    ]
