# Generated by Django 5.0.8 on 2024-09-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Singleplayer', '0010_spgame_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='spgame',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='spgame',
            name='name',
            field=models.CharField(max_length=350),
        ),
    ]
