# Generated by Django 5.0.8 on 2024-09-04 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library', '0013_alter_answer_answer_alter_answer_creator_and_more'),
        ('Singleplayer', '0011_spgame_created_date_alter_spgame_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spgame_contains_quiztask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Library.quiztask'),
        ),
    ]
